version: 2

defaults: &defaults
  docker: &ruby_image
    - &ruby_image
      image: circleci/ruby:2.5-stretch
      environment:
        RUBYOPT: '-KU -E utf-8:utf-8'
        BUNDLE_PATH: vendor/bundle
        BUNDLE_VERSION: 1.17.3
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3

filters:
  test: &filter_test
    filters:
      tags:
        ignore: /^v.*/
  beta: &filter_beta
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v[0-9]+(\.[0-9]+)+(\.[a-z].+).*/
  release: &filter_release
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v[0-9]+(\.[0-9]+)+/

workflows:
  version: 2
  build_test:
    jobs:
      - "Checkout":
          <<: *filter_test
          context: org-global
      - "Test":
          <<: *filter_test
          context: org-global
          requires:
            - "Checkout"
  build_test_beta:
    jobs:
      - "Checkout":
          <<: *filter_beta
          context: org-global
      - "Test":
          <<: *filter_beta
          context: org-global
          requires:
            - "Checkout"
      - "Publish":
          <<: *filter_beta
          context: org-global
          requires:
            - "Test"
  build_test_release:
    jobs:
      - "Checkout":
          <<: *filter_release
          context: org-global
      - "Test":
          <<: *filter_release
          context: org-global
          requires:
            - "Checkout"
      - "Publish":
          <<: *filter_release
          context: org-global
          requires:
            - "Test"

jobs:
  "Checkout":
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - checkout

      - restore_cache:
          keys:
            - sidekiq-instrumental-bundle-v2-{{ checksum "Gemfile" }}-{{ checksum "sidekiq-instrumental.gemspec" }}
      - run:
          name: Install bundler
          command: gem install bundler --version=$BUNDLE_VERSION
      - run:
          name: Bundle Install
          command: |-
            bundle _${BUNDLE_VERSION}_ check || bundle _${BUNDLE_VERSION}_ install --retry=$BUNDLE_RETRY
      - save_cache:
          key: sidekiq-instrumental-bundle-v2-{{ checksum "Gemfile" }}-{{ checksum "sidekiq-instrumental.gemspec" }}
          paths:
            - vendor/bundle
            - Gemfile.lock

      - persist_to_workspace:
          root: .
          paths: .
  "Test":
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install bundler
          command: gem install bundler --version=$BUNDLE_VERSION
      - run:
          name: RSpec
          command: bundle exec rspec
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: Build gem
          command: |-
            gem build *.gemspec
  "Publish":
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to gem server
          command: |-
            ./bin/tag_check.sh
            ./bin/setup-rubygems.sh
            rm -rf pkg
            rake build
            gem push pkg/*.gem
